# Generated by Django 3.1.4 on 2020-12-13 21:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_auto_20201213_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simple_article',
            name='simple_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
