# Generated by Django 3.1.4 on 2020-12-15 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0003_auto_20201213_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
