# Generated by Django 3.1.4 on 2020-12-17 02:18

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0004_article_reviewers'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_article_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Awaiting submission', 'Awaiting submission'), ('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Reviewed', 'Reviewed')], default='Awaiting submission', max_length=150)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='Articles.article')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_this_submission', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_this_submission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
