# Generated by Django 3.1.4 on 2020-12-18 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0006_auto_20201216_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reviewers',
            field=models.ManyToManyField(related_name='can_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
