# Generated by Django 3.1.4 on 2020-12-19 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0007_auto_20201217_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_article_submission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_this_submission', to=settings.AUTH_USER_MODEL),
        ),
    ]
