# Generated by Django 3.1.4 on 2020-12-20 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0008_auto_20201219_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approvers',
            field=models.ManyToManyField(related_name='can_approve', to=settings.AUTH_USER_MODEL),
        ),
    ]
