# Generated by Django 3.1.4 on 2020-12-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0009_article_approvers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_article_submission',
            name='status',
            field=models.CharField(choices=[('Awaiting submission', 'Awaiting submission'), ('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved')], default='Awaiting submission', max_length=150),
        ),
    ]
